### ISSUE TITLE
test failing

### ISSUE THREAD

**Issue by michela** [Indigemoji-Australia/indigemoji-app#10]
```
kai:indigemoji-app michela$ yarn run test
yarn run v1.21.1
$ jest
 FAIL  __tests__/App-test.js
  ● Test suite failed to run

    Jest encountered an unexpected token

    This usually means that you are trying to import a file which Jest cannot parse, e.g. it's not plain JavaScript.

    By default, if Jest sees a Babel config, it will use that to transform your files, ignoring "node_modules".

    Here's what you can do:
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/en/configuration.html

    Details:

    /Users/michela/git/indigemoji-app/node_modules/react-navigation/src/react-navigation.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export * from '@react-navigation/core';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token 'export'

      1 | import React from 'react';
      2 | import {Image} from 'react-native';
    > 3 | import {createAppContainer} from 'react-navigation';
        | ^
      4 | import {createStackNavigator} from 'react-navigation-stack';
      5 | import {createDrawerNavigator} from 'react-navigation-drawer';
      6 | import HomeScreen from './screens/Home';

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at Object.<anonymous> (App.js:3:1)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        0.583s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
kai:indigemoji-app michela$ 
```

**Comment by michela** [comment]
Unit test for QA
